#+author: conao3
#+date: <2020-03-20 Fri>

[[https://github.com/conao3/smear-cursor.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/smear-cursor.el.png]]
[[https://github.com/conao3/smear-cursor.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/smear-cursor.el.svg?style=flat-square]]
[[https://github.com/conao3/smear-cursor.el/releases][https://img.shields.io/github/tag/conao3/smear-cursor.el.svg?style=flat-square]]
[[https://github.com/conao3/smear-cursor.el/actions][https://github.com/conao3/smear-cursor.el/actions/workflows/test.yml/badge.svg]]
[[https://app.codacy.com/project/conao3/smear-cursor.el/dashboard][https://img.shields.io/codacy/grade/62a36f4f04524d5e8c758440e8071c45.svg?logo=codacy&style=flat-square]]
[[https://www.patreon.com/conao3][https://img.shields.io/badge/patreon-become%20a%20patron-orange.svg?logo=patreon&style=flat-square]]
[[https://twitter.com/conao_3][https://img.shields.io/badge/twitter-@conao__3-blue.svg?logo=twitter&style=flat-square]]


* Table of Contents
- [[#description][Description]]
- [[#install][Install]]
- [[#usage][Usage]]
- [[#customize][Customize]]
- [[#information][Information]]
  - [[#community][Community]]
  - [[#contribution][Contribution]]
  - [[#migration][Migration]]
  - [[#license][License]]
  - [[#author][Author]]
  - [[#contributors][Contributors]]

* Description
[[https://github.com/conao3/smear-cursor.el][https://raw.githubusercontent.com/conao3/files/master/blob/smear-cursor.el/smear-cursor.gif]]

Renders smear trail behind the cursor.

Ported from [[https://github.com/mattn/vim-smear-cursor][vim-smear-cursor]] by mattn, which was inspired by [[https://github.com/sphamba/smear-cursor.nvim][smear-cursor.nvim]].

Uses 1/8 block characters (▁▂▃▄▅▆▇█) rendered as buffer overlays with a
6-level brightness gradient.  The trail is progressively erased via a
repeating timer, tail-first.

* Install
Sample install code using [[https://github.com/conao3/leaf.el][leaf.el]].

#+begin_src emacs-lisp
  (leaf smear-cursor :ensure t)
#+end_src

* Usage
Enable the global minor mode:

#+begin_src emacs-lisp
  (smear-cursor-mode 1)
#+end_src

Or with [[https://github.com/conao3/leaf.el][leaf.el]]:

#+begin_src emacs-lisp
  (leaf smear-cursor
    :ensure t
    :global-minor-mode smear-cursor-mode)
#+end_src

* Customize
| Variable                          | Default | Description                                      |
|-----------------------------------+---------+--------------------------------------------------|
| ~smear-cursor-erase-interval~     | ~0.01~  | Seconds between animation erase steps            |
| ~smear-cursor-min-distance~       | ~3~     | Minimum movement distance to trigger the effect  |
| ~smear-cursor-aspect~             | ~2.0~   | Row/column aspect ratio correction               |
| ~smear-cursor-head-width~         | ~0.9~   | Smear half-width at head (new cursor position)   |
| ~smear-cursor-tail-width~         | ~0.1~   | Smear half-width at tail (old cursor position)   |

Faces ~smear-cursor-lv1~ through ~smear-cursor-lv6~ control the brightness
gradient from head (bright) to tail (dim).

* Information
** Community
Any feedback or suggestions are welcome!

You can use github issues.

** Contribution
We welcome PR!

*** Require tools for testing
- keg
  #+begin_src shell
    cd ~/
    gh repo clone conao3/keg .keg
    export PATH="$HOME/.keg/bin:$PATH"
  #+end_src

*** Running test
Below operation flow is recommended.
#+begin_src shell
  git branch [feature-branch]       # Create branch named [feature-branch]
  git checkout [feature-branch]     # Checkout branch named [feature-branch]

  # <edit loop>
  emacs smear-cursor.el             # Edit something you want

  make test                         # Test smear-cursor
  git commit -am "brabra"           # Commit (auto-run test before commit)
  # </edit loop>

  gh repo fork                      # Create fork at GitHub
  git push [user] [feature-branch]  # Push feature-branch to your fork
  gh pr create                      # Create pull-request
#+end_src

** Migration

** License
#+begin_example
  General Public License Version 3 (GPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/smear-cursor.el/blob/master/LICENSE
#+end_example

This package is a port of [[https://github.com/mattn/vim-smear-cursor][vim-smear-cursor]] by mattn, originally licensed under MIT.

** Author
- Naoya Yamashita ([[https://github.com/conao3][conao3]])

** Contributors
